### ISSUE TITLE
(3)undefined method `node?' while editing works

### ISSUE THREAD

**Issue by rschwab** [UCSCLibrary/ucsc-library-digital-collections#541]
While [editing a work](https://digitalcollections.library.ucsc.edu/concern/works/rb68xg630/edit?locale=en) I encountered this error:
ActionView::Template::Error (undefined method `node?' for "http://id.loc.gov/authorities/names/n82217191":String):

It seems to be related to controlled vocab fields on the work edit form.

Here's the (partially edited for readability) log output:
```
F, [2023-01-03T15:55:24.635991 #6407] FATAL -- : ActionView::Template::Error (undefined method `node?' for "http://id.loc.gov/authorities/names/n82217191":String):
F, [2023-01-03T15:55:24.636097 #6407] FATAL -- :
 8:   <% end %>
 9: <% else %>
10: <%#= This is the field that will apply where ScoobySnacks is being used %>
11:   <%= f.input key, input_options %>
12: <% end %>
F, [2023-01-03T15:55:24.636120 #6407] FATAL -- : 
F, [2023-01-03T15:55:24.636146 #6407] FATAL -- : app/inputs/textbox_autosuggest_input.rb:5:in `build_field'
app/views/records/edit_fields/_default.html.erb:11:in `_app_views_records_edit_fields__default_html_erb___1259948538139581249_2050500'
app/helpers/ucsc_records_helper.rb:63:in `render_edit_field_partial_ucsc'
app/views/hyrax/base/_form_metadata.html.erb:6:in `block in _app_views_hyrax_base__form_metadata_html_erb__4424294574010751175_2050480'
app/views/hyrax/base/_form_metadata.html.erb:5:in `each'
app/views/hyrax/base/_form_metadata.html.erb:5:in `_app_views_hyrax_base__form_metadata_html_erb__4424294574010751175_2050480'
app/views/hyrax/works/edit.html.erb:19:in `_app_views_hyrax_works_edit_html_erb__2288992654907941586_2050120'
```

**Comment by rschwab** [comment]
I don't see this error anymore.
