### ISSUE TITLE
(4)Ldp::HttpError on sandbox imports

### ISSUE THREAD

**Issue by snehagunduraoUL** [UCSCLibrary/ucsc-library-digital-collections#582]
All imports are failing on sandbox. Initial guess is that its a fedora issue.
Here is the error:
http://digitalcollections-staging-sandbox.library.ucsc.edu/importers/405/entries/29087?locale=en

**Comment by rschwab** [comment]
Just for easy non-vpn reference:
```
Errored at: 2023-02-28 21:58:08 UTC

Error: Ldp::HttpError - STATUS: 500 java.lang.IllegalStateException: Transaction TransactionImple < ac, BasicAction: 0:ffff80722230:9c61:6011a21a:1ad94e status: ActionStatus.ABORTED > is not in a valid state to be invoking cache operations on. at org.infinispan.interceptors.TxInterceptor.enlist(TxInterceptor.java:389) at org.infinispan.interceptors.TxInterceptor.enlistIfNeeded(TxInterceptor.java:351) at org.infinispan.interceptors.TxInterceptor.enlistReadAndInvokeNext(TxInterceptor.java:345) at org.infinispan.interceptors.TxInterceptor.visitGetKeyValueCommand(TxInterceptor.java:318) at org.infinispan.commands.read.GetKeyValueCommand.acceptVisitor(GetKeyValueCommand.java:40) at org.infinispan.interceptors.base.CommandInterceptor.invokeNextInterceptor(CommandInterceptor.java:97) at org.infinispan.interceptors.CacheMgmtInterceptor.visitDataReadCommand(CacheMgmtInterceptor.java:103) at org.infinispan.interceptors.CacheMgmtInterceptor.visitGetKeyValueCommand(CacheMgmtInterceptor.java:91) at org.infinispan.commands.re...

Error Trace:

/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/ldp-1.0.3/lib/ldp/client/methods.rb:118:in `block in check_for_errors'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/ldp-1.0.3/lib/ldp/client/methods.rb:116:in `tap'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/ldp-1.0.3/lib/ldp/client/methods.rb:116:in `check_for_errors'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/ldp-1.0.3/lib/ldp/client/methods.rb:52:in `block in get'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:170:in `instrument'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/ldp-1.0.3/lib/ldp/client/methods.rb:32:in `get'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/caching_connection.rb:13:in `block in get'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/caching_connection.rb:67:in `block in log'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `block in instrument'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `instrument'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/caching_connection.rb:66:in `log'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/caching_connection.rb:13:in `get'
/home/hyrax/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/delegate.rb:83:in `method_missing'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/initializing_connection.rb:27:in `get'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/ldp-1.0.3/lib/ldp/resource.rb:54:in `get'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/ldp-1.0.3/lib/ldp/resource/rdf_source.rb:58:in `response_graph'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/ldp-1.0.3/lib/ldp/resource/rdf_source.rb:33:in `graph'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/default_model_mapper.rb:14:in `classifier'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:196:in `class_to_load'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:185:in `load_from_fedora'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:122:in `block (2 levels) in find_each'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:120:in `each'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:120:in `block in find_each'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:158:in `block in search_in_batches'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:154:in `loop'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:154:in `search_in_batches'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation/finder_methods.rb:119:in `find_each'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/active-fedora-12.2.3/lib/active_fedora/relation.rb:152:in `each'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/bulkrax-3.4.0/app/factories/bulkrax/object_factory.rb:89:in `detect'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/bulkrax-3.4.0/app/factories/bulkrax/object_factory.rb:89:in `search_by_identifier'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/bulkrax-3.4.0/app/factories/bulkrax/object_factory.rb:70:in `find'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/bulkrax-3.4.0/app/models/concerns/bulkrax/dynamic_record_lookup.rb:28:in `find_record'
/srv/ucsc_sufia_sandbox/releases/20230217232030/app/jobs/bulkrax/create_relationships_job.rb:19:in `block in perform'
/srv/ucsc_sufia_sandbox/releases/20230217232030/app/jobs/bulkrax/create_relationships_job.rb:17:in `each'
/srv/ucsc_sufia_sandbox/releases/20230217232030/app/jobs/bulkrax/create_relationships_job.rb:17:in `perform'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/execution.rb:39:in `block in perform_now'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `block in instrument'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `instrument'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/logging.rb:46:in `block in tag_logger'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/logging.rb:46:in `tag_logger'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/execution.rb:38:in `perform_now'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/execution.rb:24:in `block in execute'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:73:in `block in wrap'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:86:in `wrap'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:72:in `wrap'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/execution.rb:22:in `execute'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activejob-5.2.8.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:196:in `execute_job'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:163:in `block in process'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/job_retry.rb:114:in `local'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/rails.rb:14:in `block in call'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:73:in `block in wrap'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/execution_wrapper.rb:90:in `wrap'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/reloader.rb:72:in `wrap'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/rails.rb:13:in `call'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:257:in `stats'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/job_logger.rb:13:in `call'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/job_retry.rb:81:in `global'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:124:in `block in dispatch'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/logger.rb:11:in `with'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/job_logger.rb:33:in `prepare'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:123:in `dispatch'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:162:in `process'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:78:in `process_one'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/processor.rb:68:in `run'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/util.rb:56:in `watchdog'
/srv/ucsc_sufia_sandbox/shared/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/util.rb:65:in `block in safe_thread'
```

**Comment by rschwab** [comment]
From the messages log on the repo server
```
Mar  2 13:49:40 digitalcollections-repo server: ERROR 13:49:40.859 (WildcardExceptionMapper) Exception intercepted by WildcardExceptionMapper: Transaction TransactionImple < ac, BasicAction: 0:ffff80722230:9c61:6011a21a:1ad94e status: ActionStatus.ABORTED > is not in a valid state to be invoking cache operations on.
```

**Comment by rschwab** [comment]
This person found this error using fedora 4 (same major version as us) when doing large transactions. They could temporarily fix it by restarting fedora. https://groups.google.com/g/fedora-tech/c/cLcXjdyRo18?pli=1

**Comment by snehagunduraoUL** [comment]
Restarted fedora and tried a sample import.It worked. Moving this to SandboxQA-going to import the 6th spreadsheet

**Comment by snehagunduraoUL** [comment]
This error is not occurring anymore. Can be moved to done.
